plugins {
    id "base"
    id "net.fabricmc.fabric-loom-remap" version "1.18.2" apply false
    id "net.fabricmc.fabric-loom" version "1.18.2" apply false
}

allprojects {
    group = rootProject.property("maven_group")
    version = rootProject.property("mod_version")

    repositories {
        mavenCentral()
        maven {
            name = "Nucleoid"
            url = "https://maven.nucleoid.xyz/"
        }
    }
}

subprojects {
    plugins.withId("java") {
        def childBuild = tasks.named("build")
        rootProject.tasks.named("build").configure {
            dependsOn childBuild
        }
    }
}
