base {
    archivesName = "${rootProject.archives_base_name}-${target_minecraft}"
}

sourceSets {
    main {
        java.srcDir rootProject.file("common/src/main/java")
        java.srcDir rootProject.file("versions/shared/src/main/java")
        java.srcDir rootProject.file(adapter_source)
        java.srcDir rootProject.file(autohost_adapter_source)
        java.srcDir rootProject.file(mixin_source)
        java.srcDir rootProject.file(command_source)
        resources.srcDir rootProject.file("versions/shared/src/main/resources")
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${target_minecraft}"

    if (plugins.hasPlugin("net.fabricmc.fabric-loom-remap")) {
        mappings loom.officialMojangMappings()
        modImplementation "net.fabricmc:fabric-loader:${loader_version}"
        modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
        modImplementation "eu.pb4:polymer-autohost:${polymer_version}"
        modImplementation "eu.pb4:polymer-resource-pack:${polymer_version}"
    } else {
        implementation "net.fabricmc:fabric-loader:${loader_version}"
        implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
        implementation "eu.pb4:polymer-autohost:${polymer_version}"
        implementation "eu.pb4:polymer-resource-pack:${polymer_version}"
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_range", minecraft_range
    inputs.property "loader_version", loader_version
    inputs.property "polymer_version", polymer_version

    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand(
            version: project.version,
            minecraft_range: minecraft_range,
            loader_version: loader_version,
            polymer_version: polymer_version
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set(java_version as int)
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.toVersion(java_version)
    targetCompatibility = JavaVersion.toVersion(java_version)
}

jar {
    from(rootProject.file("LICENSE.txt")) {
        rename { "${it}_${project.name}" }
    }
}
