plugins {
    id "net.fabricmc.fabric-loom-remap"
}

ext {
    target_minecraft = "1.21.8"
    artifact_minecraft = "1.21.8"
    minecraft_range = ">=1.21.8 <1.21.9"
    loader_version = "0.16.14"
    fabric_api_version = "0.131.0+1.21.8"
    polymer_version = "0.13.13+1.21.8"
    java_version = 21
    adapter_source = "versions/legacy/src/main/java"
    autohost_adapter_source = "versions/autohost-resource-location/src/main/java"
    mixin_source = "versions/mixin-legacy/src/main/java"
    command_source = "versions/commands-legacy/src/main/java"
}

apply from: rootProject.file("gradle/version-module.gradle")
