plugins {
    id "net.fabricmc.fabric-loom"
}

ext {
    target_minecraft = "26.3"
    minecraft_range = ">=26.3"
    loader_version = "0.19.5"
    fabric_api_version = "0.160.5+26.3"
    polymer_version = "0.18.2+26.3"
    java_version = 25
    adapter_source = "versions/modern/src/main/java"
    autohost_adapter_source = "versions/autohost-identifier-modern/src/main/java"
}

apply from: rootProject.file("gradle/version-module.gradle")
