plugins {
    id "net.fabricmc.fabric-loom-remap"
}

ext {
    target_minecraft = "1.21.10"
    artifact_minecraft = "1.21.9-1.21.10"
    minecraft_range = ">=1.21.9 <1.21.11"
    loader_version = "0.17.2"
    fabric_api_version = "0.134.1+1.21.10"
    polymer_version = "0.14.4+1.21.10"
    java_version = 21
    adapter_source = "versions/legacy/src/main/java"
    autohost_adapter_source = "versions/autohost-resource-location/src/main/java"
    mixin_source = "versions/mixin-legacy/src/main/java"
    command_source = "versions/commands-legacy/src/main/java"
}

apply from: rootProject.file("gradle/version-module.gradle")
